---
- hosts: easafetynet
  remote_user: root
  gather_facts: no

  tasks:
  - include: easn-https-tasks.yml

  - name: Update kickbot python scripts
    synchronize:
      src: ../kickbot/
      dest: /opt/easn/kickbot/
      delete: yes
      recursive: yes
    notify: restart kickbot

  - name: Update kickbot config
    template:
      src: ../config-files/kickbot-conf.j2
      dest: /etc/easn/kickbot.conf
    notify: restart kickbot

  - name: Update kickbot systemd unit
    synchronize:
      src: ../config-files/kickbot.service
      dest: /etc/systemd/system/kickbot.service
    notify:
    - daemon reload
    - restart kickbot

  handlers:
    - include: easn-handlers.yml
