---
- hosts: easafetynet
  remote_user: root
  gather_facts: no
  become: yes
  become_user: postgres

  tasks:
  - name: Create postgresql db
    postgresql_db:
      name: easn

  - name: Create postgresql migration user
    postgresql_user:
      db: easn
      name: migration
      password: "{{ db_migration_password }}"
      role_attr_flags: "NOSUPERUSER,NOCREATEDB,LOGIN"
      priv: "ALL"

- hosts: easafetynet
  remote_user: root
  gather_facts: no

  tasks:
  - include: easn-https-tasks.yml

  - name: Update index.html
    template:
      src: ../web/index.j2
      dest: /var/www/easn/index.html

  - name: Update static web assets
    synchronize:
      src: ../web/static/
      dest: /var/www/easn/static/
      delete: yes
      recursive: yes

  - name: Update userpage python scripts
    synchronize:
      src: ../userpage/
      dest: /opt/easn/userpage/
      delete: yes
      recursive: yes
    notify:
    - data migration
    - restart userpage

  - name: Update userpage config
    template:
      src: ../config-files/userpage-conf.j2
      dest: /etc/easn/userpage.conf
    notify: restart userpage

  - name: Update userpage systemd unit
    synchronize:
      src: ../config-files/userpage.service
      dest: /etc/systemd/system/userpage.service
    notify:
    - daemon reload
    - restart userpage

  handlers:
    - include: easn-handlers.yml

