---
- name: restart nginx
  command: nginx -s reload

- name: daemon reload
  command: systemctl daemon-reload

- name: restart services
  service:
    name: kickbot
    state: restarted

- name: restart userpage
  service:
    name: userpage
    state: restarted

