---
- hosts: easafetynet
  remote_user: root
  gather_facts: no

  pre_tasks:
  - name: make sure python 2 is installed
    raw: apt-get install -y python-simplejson

  tasks:
  - name: NGINX | Updating apt cache
    apt:
      update_cache: yes
 
  - name: NGINX | Installing NGINX
    apt:
      pkg: nginx
      state: latest
 
  - name: NGINX | Starting NGINX
    service:
      name: nginx
      state: started

  - template:
      src: ../config-files/nginx-http.j2
      dest: /etc/nginx/sites-available/easn-http
    notify: "restart nginx"

  - template:
      src: ../config-files/nginx-https.j2
      dest: /etc/nginx/sites-available/easn-https
    notify: "restart nginx"

  - file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: "restart nginx"

  - file:
      src: /etc/nginx/sites-available/easn-http
      dest: /etc/nginx/sites-enabled/easn-http
      state: link
    notify: "restart nginx"

  - name: Create etc/easn
    file:
      path: /etc/easn
      state: directory

  - name: install pip
    apt:
      name: python3-pip

  - name: pip jsonschema
    pip:
      executable: pip3
      name: jsonschema

  handlers:
    - include: easn-handlers.yml
