---
- hosts: easafetynet
  remote_user: root
  gather_facts: no
  become: yes
  become_user: postgres

  tasks:
  - name: Create postgresql db
    postgresql_db:
      name: easn

  - name: Create postgresql migration user
    postgresql_user:
      db: easn
      name: migration
      password: "{{ db_migration_password }}"
      role_attr_flags: "NOSUPERUSER,NOCREATEDB,LOGIN"
      priv: "ALL"

  - name: Create postgresql app user
    postgresql_user:
      db: easn
      name: app
      password: "{{ db_app_password }}"
      role_attr_flags: "NOSUPERUSER,NOCREATEDB,LOGIN"
      priv: "ALL"

  - name: Set table access privileges for app user
    postgresql_privs:
      state: present
      database: easn
      privs: SELECT,INSERT,UPDATE
      type: table
      objs: ALL_IN_SCHEMA
      schema: public
      roles: app
      grant_option: yes

  - name: Set sequence access privileges for app user
    postgresql_privs:
      state: present
      database: easn
      privs: SELECT,UPDATE
      type: sequence
      objs: ALL_IN_SCHEMA
      schema: public
      roles: app
      grant_option: yes

- hosts: easafetynet
  remote_user: root
  gather_facts: no

  tasks:
  - include: https-tasks.yml

  - name: Update index.html
    template:
      src: ../web/index.j2
      dest: /var/www/easn/index.html

  - name: Update userpage config
    template:
      src: ../config-files/userpage-conf.j2
      dest: /etc/easn/userpage.conf
    notify: restart userpage

  - include: topup.yml

  - name: Update userpage systemd unit
    synchronize:
      src: ../config-files/userpage.service
      dest: /etc/systemd/system/userpage.service
    notify:
    - daemon reload
    - restart userpage

  handlers:
    - include: handlers.yml

